import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Image from 'next/image'
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from '../../styles/Home.module.css'

const PokemonName: NextPage = () => {
  const router = useRouter()
  const [pokemon, setPokemon] = useState<Pokemon>();
  
  useEffect(() => {   
    if (!router.isReady) return;

    const find = async () => {
    const { pokemonName } = router.query
    const response = await axios.get(`http://localhost:3000/api/pokemon/${pokemonName}`);
    return response.data;
   }

   find().then(data => {
    setPokemon(data);
   });
  }, [router.isReady, router.query]);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {pokemon && (
          <div key={pokemon.id} className={styles.card}>
            <h3>{pokemon.name}</h3>
            <Image width={96} height={96} src={pokemon.image} alt={pokemon.name} />
            <p>Height: {pokemon.height}</p>
            <p>Weight: {pokemon.weight}</p>
            <p>Types: {pokemon.types.join(", ")}</p>
          </div>
        )}
        <button onClick={() => router.push("/")}>Back</button>
      </main>
    </div>
  );
};

export default PokemonName;
