import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Image from 'next/image'
import { useRouter } from "next/router";
import NotFound from "../../components/NotFound";
import styles from '../../styles/Home.module.css'

const PokemonName: NextPage = ({ pokemon }: any) => {
  const router = useRouter()
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {pokemon ? (
          <>
            <div className={styles.header}>
              <button onClick={() => router.push("/")}>{"<"}</button>
              <h3>{pokemon.name}</h3>
            </div>
            <div className={styles.card}> 
              <div className={styles.card_item}>
                <Image className={styles.card_item} width={96} height={96} src={pokemon.image} alt={pokemon.name} />
              </div>
              <div className={styles.card_item}>
                <p>Height: {pokemon.height}</p>
                <p>Weight: {pokemon.weight}</p>
                <p>Types: {pokemon.types.join(", ")}</p>
              </div>
            </div>
          </>
        ) : <NotFound />}
      </main>
    </div>
  );
};

export async function getServerSideProps(ctx: any) {
  const pokemonName: string = ctx.params.pokemonName;
  const baseUrl = process.env.NEXT_API_BASE_URL;
  try {
    const response = await axios.get<Pokemon>(`${baseUrl}pokemon/${pokemonName}`);
    
    return {
      props: { pokemon: response.data },
    }
  } catch {
    return {
      props: { pokemon: null },
    }
  }
}

export default PokemonName;
